/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import database.admindatabasesms;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import studentmanagementsystem.adminloginsms;

/**
 *
 * @author GOVIND SINGLA
 */
public class adminstartsms extends javax.swing.JFrame {
String s,n,p,sub,cont,subcode,gmail,my_bio;
String s1,s2,s3,s4,s5,s6,s7,s8, exi;
ImageIcon icon;
boolean exist_boolean = false;

    

    /**
     * Creates new form adminstartsms
     */
    public adminstartsms() {
        
        initComponents();
        
    }
    
    public adminstartsms(String username)
{
    
        s=username;
        try(
                Connection con=admindatabasesms.getConnect();
                PreparedStatement ps=con.prepareStatement("select * from admin where username='"+s+"'");
                ResultSet rs=ps.executeQuery();
                )
            {
                if(rs.next())
                {
                   n =  rs.getString("name");
                    p =  rs.getString("password");
                    sub =  rs.getString("subject");
                    cont =  rs.getString("contact");
                    subcode =  rs.getString("subjectcode");
                  gmail = rs.getString("gmail");
                my_bio = rs.getString("bio");
                 String check=String.valueOf(rs.getBinaryStream("image"));
                 if(check == "null")
                 {
                            icon=new ImageIcon("C:\\Users\\GOVIND SINGLA\\Downloads\\noimage.png");
                 }
                 else
                 {
                        BufferedImage imag=ImageIO.read(rs.getBinaryStream("image"));
                         Image image = imag;
                         Image iag = image.getScaledInstance(290, 260 , Image.SCALE_SMOOTH);
                         icon =new ImageIcon(iag);
                 } 
                }
            } 
        catch (Exception e)
        {
            e.printStackTrace();
        }
                initComponents();
exist_label.setVisible(false);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        home = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        pincode = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        USERNAME = new javax.swing.JTextField();
        NAME = new javax.swing.JTextField();
        PINCODE = new javax.swing.JTextField();
        AGE = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ADDRESS = new javax.swing.JTextArea();
        MALE = new javax.swing.JRadioButton();
        FEMALE = new javax.swing.JRadioButton();
        PASSWORD = new javax.swing.JPasswordField();
        exist_label = new javax.swing.JLabel();
        Register = new javax.swing.JButton();
        CONTACT = new javax.swing.JTextField();
        Clear = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        add_file_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        editprofile = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        imglabel = new javax.swing.JLabel();
        changeimage = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        addbio = new javax.swing.JTextArea();
        change_image = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1267, 885));
        setUndecorated(true);

        home.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1265, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );

        home.addTab("Home", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(null);

        jPanel7.setBackground(new java.awt.Color(43, 27, 23));

        username.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Username");

        name.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Name");

        password.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password");

        dob.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        dob.setForeground(new java.awt.Color(255, 255, 255));
        dob.setText("Age");

        gender.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        gender.setForeground(new java.awt.Color(255, 255, 255));
        gender.setText("Gender");

        contact.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        contact.setForeground(new java.awt.Color(255, 255, 255));
        contact.setText("Contact");

        pincode.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        pincode.setForeground(new java.awt.Color(255, 255, 255));
        pincode.setText("Pin Code");

        address.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setText("Address");

        USERNAME.setBackground(new java.awt.Color(61, 60, 58));
        USERNAME.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        USERNAME.setForeground(new java.awt.Color(255, 255, 255));
        USERNAME.setCaretColor(new java.awt.Color(255, 255, 255));
        USERNAME.setDisabledTextColor(new java.awt.Color(153, 255, 255));
        USERNAME.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                USERNAMEFocusGained(evt);
            }
        });
        USERNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERNAMEActionPerformed(evt);
            }
        });
        USERNAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                USERNAMEKeyReleased(evt);
            }
        });

        NAME.setBackground(new java.awt.Color(61, 60, 58));
        NAME.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        NAME.setForeground(new java.awt.Color(255, 255, 255));
        NAME.setCaretColor(new java.awt.Color(255, 255, 255));
        NAME.setDisabledTextColor(new java.awt.Color(153, 255, 255));
        NAME.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NAMEFocusGained(evt);
            }
        });
        NAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMEActionPerformed(evt);
            }
        });

        PINCODE.setBackground(new java.awt.Color(61, 60, 58));
        PINCODE.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        PINCODE.setForeground(new java.awt.Color(255, 255, 255));
        PINCODE.setCaretColor(new java.awt.Color(255, 255, 255));
        PINCODE.setDisabledTextColor(new java.awt.Color(153, 255, 255));
        PINCODE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PINCODEFocusGained(evt);
            }
        });
        PINCODE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PINCODEActionPerformed(evt);
            }
        });
        PINCODE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PINCODEKeyTyped(evt);
            }
        });

        AGE.setBackground(new java.awt.Color(61, 60, 58));
        AGE.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        AGE.setForeground(new java.awt.Color(255, 255, 255));
        AGE.setCaretColor(new java.awt.Color(255, 255, 255));
        AGE.setDisabledTextColor(new java.awt.Color(153, 255, 255));
        AGE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AGEFocusGained(evt);
            }
        });
        AGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGEActionPerformed(evt);
            }
        });
        AGE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AGEKeyTyped(evt);
            }
        });

        ADDRESS.setBackground(new java.awt.Color(61, 60, 58));
        ADDRESS.setColumns(20);
        ADDRESS.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ADDRESS.setForeground(new java.awt.Color(255, 255, 255));
        ADDRESS.setRows(5);
        ADDRESS.setCaretColor(new java.awt.Color(255, 255, 255));
        ADDRESS.setDisabledTextColor(new java.awt.Color(153, 255, 255));
        jScrollPane2.setViewportView(ADDRESS);

        MALE.setBackground(new java.awt.Color(61, 60, 58));
        buttonGroup2.add(MALE);
        MALE.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        MALE.setForeground(new java.awt.Color(255, 255, 255));
        MALE.setText("Male");

        FEMALE.setBackground(new java.awt.Color(61, 60, 58));
        buttonGroup2.add(FEMALE);
        FEMALE.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        FEMALE.setForeground(new java.awt.Color(255, 255, 255));
        FEMALE.setText("Female");

        PASSWORD.setBackground(new java.awt.Color(61, 60, 58));
        PASSWORD.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        PASSWORD.setForeground(new java.awt.Color(255, 255, 255));
        PASSWORD.setCaretColor(new java.awt.Color(255, 255, 255));
        PASSWORD.setDisabledTextColor(new java.awt.Color(153, 255, 255));
        PASSWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASSWORDActionPerformed(evt);
            }
        });

        exist_label.setBackground(new java.awt.Color(61, 60, 58));
        exist_label.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        exist_label.setForeground(new java.awt.Color(255, 255, 255));
        exist_label.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                exist_labelKeyReleased(evt);
            }
        });

        Register.setBackground(new java.awt.Color(61, 60, 58));
        Register.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Register.setForeground(new java.awt.Color(255, 255, 255));
        Register.setText("Register");
        Register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });

        CONTACT.setBackground(new java.awt.Color(61, 60, 58));
        CONTACT.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        CONTACT.setForeground(new java.awt.Color(255, 255, 255));
        CONTACT.setCaretColor(new java.awt.Color(255, 255, 255));
        CONTACT.setDisabledTextColor(new java.awt.Color(153, 255, 255));
        CONTACT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CONTACTFocusGained(evt);
            }
        });
        CONTACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONTACTActionPerformed(evt);
            }
        });
        CONTACT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CONTACTKeyTyped(evt);
            }
        });

        Clear.setBackground(new java.awt.Color(61, 60, 58));
        Clear.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Clear.setForeground(new java.awt.Color(255, 255, 255));
        Clear.setText("Clear");
        Clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addComponent(exist_label, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(USERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(MALE, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(FEMALE, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(pincode, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(PINCODE, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(132, 132, 132)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AGE, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CONTACT, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(Register, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(126, 126, 126))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(exist_label, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(USERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AGE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CONTACT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MALE)
                    .addComponent(FEMALE))
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pincode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PINCODE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Register, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        jPanel3.add(jPanel7);
        jPanel7.setBounds(240, 80, 813, 744);

        home.addTab("Add Student", jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        add_file_button.setBackground(new java.awt.Color(61, 60, 58));
        add_file_button.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        add_file_button.setForeground(new java.awt.Color(255, 255, 255));
        add_file_button.setText("Add File");
        add_file_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_file_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_file_buttonActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(61, 60, 58));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(add_file_button, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(562, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(add_file_button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(696, Short.MAX_VALUE))
        );

        home.addTab("Academic Section", jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jPanel6.setBackground(new java.awt.Color(43, 27, 23));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 29)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 29)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 29)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Name");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 29)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Contact");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 29)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Subject");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 29)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Subject Code");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 29)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(s);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 29)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("G-Mail");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 29)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(sub
        );

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 29)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(n
        );

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 29)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(subcode

        );

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 29)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText(gmail);

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 29)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText(p);

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 29)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText(cont);

        editprofile.setBackground(new java.awt.Color(61, 60, 58));
        editprofile.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        editprofile.setForeground(new java.awt.Color(255, 255, 255));
        editprofile.setText("Edit Profile");
        editprofile.setFocusPainted(false);
        editprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editprofileActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(61, 60, 58));
        logout.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.setFocusPainted(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(editprofile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel10))
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel9))
                .addGap(37, 37, 37)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel11))
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel13))
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel15))
                .addGap(125, 125, 125))
        );

        imglabel.setIcon(icon);

        changeimage.setBackground(new java.awt.Color(61, 60, 58));
        changeimage.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        changeimage.setForeground(new java.awt.Color(255, 255, 255));
        changeimage.setText("Add Bio");
        changeimage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changeimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeimageActionPerformed(evt);
            }
        });

        addbio.setBackground(new java.awt.Color(61, 60, 58));
        addbio.setColumns(20);
        addbio.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        addbio.setForeground(new java.awt.Color(255, 255, 255));
        addbio.setRows(5);
        addbio.setText(my_bio);
        addbio.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(addbio);

        change_image.setBackground(new java.awt.Color(61, 60, 58));
        change_image.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        change_image.setForeground(new java.awt.Color(255, 255, 255));
        change_image.setText("change image");
        change_image.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        change_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_imageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(imglabel))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changeimage)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(108, 108, 108)
                    .addComponent(change_image)
                    .addContainerGap(996, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(imglabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(changeimage, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(102, 102, 102)
                    .addComponent(change_image, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(723, Short.MAX_VALUE)))
        );

        home.addTab("Profile", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editprofileActionPerformed
                editadminsms es=new editadminsms(s);
                es.setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_editprofileActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
           int i= JOptionPane.showConfirmDialog(null, "Are you sure you want to logout");
            if (i == 0) 
            {
                        adminloginsms als=new adminloginsms();
                        als.setVisible(true);
                        setVisible(false);
            }
            
    }//GEN-LAST:event_logoutActionPerformed

    private void changeimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeimageActionPerformed
        
        String bio = addbio.getText();
        try(
                Connection con=admindatabasesms.getConnect();
                PreparedStatement ps=con.prepareStatement("update admin set bio=? where username=?");
                )
            {
                ps.setString(1, bio);
                ps.setString(2, s);
               int j= ps.executeUpdate();
               if(j == 1)
               {
                   JOptionPane.showMessageDialog(null, "Bio added successfully");
                 
                }
            } 
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_changeimageActionPerformed

    private void change_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_imageActionPerformed
        changeimagesms ci=new changeimagesms(s, icon);
        ci.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_change_imageActionPerformed

    private void USERNAMEFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_USERNAMEFocusGained

    }//GEN-LAST:event_USERNAMEFocusGained

    private void USERNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERNAMEActionPerformed

    }//GEN-LAST:event_USERNAMEActionPerformed

    private void NAMEFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NAMEFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMEFocusGained

    private void NAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMEActionPerformed

    private void PINCODEFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PINCODEFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_PINCODEFocusGained

    private void PINCODEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PINCODEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PINCODEActionPerformed

    private void AGEFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AGEFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_AGEFocusGained

    private void AGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGEActionPerformed

    }//GEN-LAST:event_AGEActionPerformed

    private void exist_labelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_exist_labelKeyReleased
        
    }//GEN-LAST:event_exist_labelKeyReleased

    private void USERNAMEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_USERNAMEKeyReleased
       
        String a=USERNAME.getText();
        try (
                            Connection con=admindatabasesms.getConnect();
                            PreparedStatement ps=con.prepareStatement("select * from student where username = '"+a+"'");
                               ResultSet rs=ps.executeQuery();
                )
        {
            
                    if(rs.next())
                    {
                                exist_label.setVisible(true);
                                exist_label.setText("username already exist");
                                exist_boolean = true;
                    }
                    else
                    {
                                exist_boolean = false;
                                 exist_label.setVisible(false);
                    }
        } 
        catch (Exception e) 
        {
                e.printStackTrace();
        }
        
    }//GEN-LAST:event_USERNAMEKeyReleased

    private void AGEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AGEKeyTyped
    
        if(!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_AGEKeyTyped

    private void PINCODEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PINCODEKeyTyped
       
        if(!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_PINCODEKeyTyped

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
            
        s1=USERNAME.getText();
        s2=NAME.getText();
        s3=PASSWORD.getText();
        s4=AGE.getText();
        s5=CONTACT.getText();
        if(MALE.isSelected())
        {
                s6="Male";
        }
        else
        {
                s6="Female";
        }
        
        s7=PINCODE.getText();
        s8=ADDRESS.getText();
        
        if(s1.length()==0 || s2.length()==0 ||  s3.length()==0 ||  s4.length()==0 ||  s5.length()==0 || s6.length()==0 || s7.length()==0 || s8.length()==0 )
        {
             JOptionPane.showMessageDialog(null, "Please fill all the Details");
        }
        
        else if(exist_boolean)
        {
                JOptionPane.showMessageDialog(null, "username already exist ");
        }
        
        else
        {
        try(
                        Connection con=admindatabasesms.getConnect();
                         PreparedStatement ps=con.prepareStatement("insert into student values(?, ?,  ?, ?, ?, ?, ? , ?)");
              ) 
        {
                        ps.setString(1, s1);
                         ps.setString(2, s2);
                        ps.setString(3, s3);
                        ps.setString(4, s4);
                        ps.setString(5, s5);
                        ps.setString(6, s6);
                        ps.setString(7, s7);
                        ps.setString(8, s8);
                        int i = ps.executeUpdate();
                         
                        if(i>0)
                        {
                            JOptionPane.showMessageDialog(null, "Successfully Registered");
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "error");
                        }                         
        } 
        catch (Exception e) 
        {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_RegisterActionPerformed

    private void CONTACTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CONTACTFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_CONTACTFocusGained

    private void CONTACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONTACTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CONTACTActionPerformed

    private void CONTACTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CONTACTKeyTyped
            if(!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_CONTACTKeyTyped

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
            
           USERNAME.setText("");
           PASSWORD.setText("");
            NAME.setText("");
            CONTACT.setText("");
            PINCODE.setText("");
            ADDRESS.setText("");
            AGE.setText("");
  
    }//GEN-LAST:event_ClearActionPerformed

    private void add_file_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_file_buttonActionPerformed
      
        
        
    }//GEN-LAST:event_add_file_buttonActionPerformed

    private void PASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASSWORDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PASSWORDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminstartsms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminstartsms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminstartsms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminstartsms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminstartsms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ADDRESS;
    private javax.swing.JTextField AGE;
    private javax.swing.JTextField CONTACT;
    private javax.swing.JButton Clear;
    private javax.swing.JRadioButton FEMALE;
    private javax.swing.JRadioButton MALE;
    private javax.swing.JTextField NAME;
    private javax.swing.JPasswordField PASSWORD;
    private javax.swing.JTextField PINCODE;
    private javax.swing.JButton Register;
    private javax.swing.JTextField USERNAME;
    private javax.swing.JButton add_file_button;
    private javax.swing.JTextArea addbio;
    private javax.swing.JLabel address;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton change_image;
    private javax.swing.JButton changeimage;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel dob;
    private javax.swing.JButton editprofile;
    private javax.swing.JLabel exist_label;
    private javax.swing.JLabel gender;
    private javax.swing.JTabbedPane home;
    private javax.swing.JLabel imglabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton logout;
    private javax.swing.JLabel name;
    private javax.swing.JLabel password;
    private javax.swing.JLabel pincode;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables

    private static class bar {

        public bar() {
        }
    }
}
