/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagementsystem;

import database.admindatabasesms;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author GOVIND SINGLA
 */
public class trial extends javax.swing.JFrame {
File file;
String s;
ImageIcon i;
    /**
     * Creates new form trial
     */
    public trial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_file_button = new javax.swing.JButton();
        add_file_label = new javax.swing.JLabel();
        upload_file_button = new javax.swing.JButton();
        retrieve_file = new javax.swing.JButton();
        add_file_label1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        add_file_button.setBackground(new java.awt.Color(61, 60, 58));
        add_file_button.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        add_file_button.setForeground(new java.awt.Color(255, 255, 255));
        add_file_button.setText("Add File");
        add_file_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_file_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_file_buttonActionPerformed(evt);
            }
        });

        add_file_label.setBackground(new java.awt.Color(61, 60, 58));
        add_file_label.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        upload_file_button.setBackground(new java.awt.Color(61, 60, 58));
        upload_file_button.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        upload_file_button.setForeground(new java.awt.Color(255, 255, 255));
        upload_file_button.setText("upload file");
        upload_file_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        upload_file_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upload_file_buttonActionPerformed(evt);
            }
        });

        retrieve_file.setBackground(new java.awt.Color(61, 60, 58));
        retrieve_file.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        retrieve_file.setForeground(new java.awt.Color(255, 255, 255));
        retrieve_file.setText("retrieve file");
        retrieve_file.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        retrieve_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrieve_fileActionPerformed(evt);
            }
        });

        add_file_label1.setBackground(new java.awt.Color(61, 60, 58));
        add_file_label1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        add_file_label1.setText("jadsfdjsfs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(add_file_label, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(359, 359, 359)
                .addComponent(add_file_button, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(upload_file_button, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(203, 203, 203)
                    .addComponent(retrieve_file, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(457, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(417, Short.MAX_VALUE)
                    .addComponent(add_file_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(163, 163, 163)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(add_file_button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(add_file_label, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(upload_file_button, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(338, Short.MAX_VALUE)
                    .addComponent(retrieve_file, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(122, 122, 122)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(add_file_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(193, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_file_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_file_buttonActionPerformed
        JFileChooser fc=new JFileChooser();
        int i = fc.showOpenDialog(rootPane);
        if(i != JFileChooser.APPROVE_OPTION)
        {
            int j = 0;
        }
        else
        {
            try {
                 file=fc.getSelectedFile();
       add_file_label.setIcon(new ImageIcon(new ImageIcon(file.getAbsolutePath()).getImage().getScaledInstance(240, 240, Image.SCALE_DEFAULT)));

            } 
            catch (Exception e) 
            {
                e.printStackTrace();
            }
            
        }

    }//GEN-LAST:event_add_file_buttonActionPerformed

    private void upload_file_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upload_file_buttonActionPerformed
                 FileReader fr=null;
        try 
        {
            fr=new FileReader(file);
        } 
        catch (Exception e) 
        {
            e.printStackTrace();
        }
        try(
                Connection con=admindatabasesms.getConnect();
                PreparedStatement ps=con.prepareStatement("insert into admin2 values(?)");
                )
            {
                
               ps.setCharacterStream(1,fr,(int)file.length());
               int i= ps.executeUpdate();
                if(i == 1)
                {
                    JOptionPane.showMessageDialog(null, "success");
                }
                else{
                     JOptionPane.showMessageDialog(null, "error");
                }
            } 
        catch (Exception e)
        {
    }
    }//GEN-LAST:event_upload_file_buttonActionPerformed

    private void retrieve_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrieve_fileActionPerformed
        
        try(
                Connection con=admindatabasesms.getConnect();
                PreparedStatement ps=con.prepareStatement("select * from admin2");
                ResultSet rs=ps.executeQuery();
                )
            {
                if(rs.next())
                {
                    
                }
             
            } 
        catch (Exception e)
        {
    }
        
    }//GEN-LAST:event_retrieve_fileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_file_button;
    private javax.swing.JLabel add_file_label;
    private javax.swing.JLabel add_file_label1;
    private javax.swing.JButton retrieve_file;
    private javax.swing.JButton upload_file_button;
    // End of variables declaration//GEN-END:variables
}
